### PR TITLE
[WiP] Fixes for StepExecutionIterator

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-26163](https://issues.jenkins-ci.org/browse/JENKINS-26163) appears to be blocking https://github.com/jenkinsci/ssh-agent-plugin/pull/4.

- [X] a test
- [ ] extend API to somehow indicate running block-scoped executions
- [ ] implement `WaitForConditionStepTest.restartDuringDelay`
- [ ] make sure `TimeoutStepTest` checks `onResume`

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Conversation with @kohsuke: currently outer `StepExecution`s are not saved at all. `CpsThread.setStep(StepExecution)` needs to be modified to keep a `Stack<StepExecution>`, and `CpsThread` needs to track a parent thread so we can walk up across `parallel` blocks.

**Comment by recena** [comment]
@jglick I'm working on: make sure `TimeoutStepTest` checks `onResume`. Ok?

**Comment by jglick** [comment]
@recena sure, just need to convert to use `RestartableJenkinsRule`, reproduce what I suspect is the bug resulting from a failure of `onResume` to be called, and `@Ignore("TODO …")` it.

**Comment by jglick** [comment]
@recena I did not file this as a branch in `origin`, so you can either file a PR-on-a-PR, or I can push this into the `origin` repo to make it easier to collaborate.

**Comment by jglick** [comment]
#161 from an `origin` branch.

**Comment by jglick** [comment]
#161 from an `origin` branch.

**Pull request closed without merging**
