### PR TITLE
[JENKINS-26399] Standard test utils

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-26399](https://issues.jenkins-ci.org/browse/JENKINS-26399)

Use standard test utilities now that we can. @reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
:bee:

**Comment by jglick** [comment]
@recena BTW technical tip: comment on lines in the PR diff tab (`…/files` URL) rather than on containing commits. This ensures that if and when the line comment is requested, GitHub will mark it as a “comment on an outdated diff”.

**Comment by jglick** [comment]
@recena not sure what you mean. [This line](https://github.com/jglick/workflow-plugin/blob/a3ed2b49c91c5e62b179eb3f378068e7c1e7601e/aggregator/src/test/java/org/jenkinsci/plugins/workflow/JenkinsRuleExt.java#L64) uses the import.

**Comment by recena** [comment]
@jglick What is a right way to add a comment to line of code?

**Comment by recena** [comment]
@jglick Ok, after to talk with @amuniz I understand what do you want to tell me. Thanks.

**Comment by recena** [comment]
@jglick Try to compile after removing the import and you'll be surprised ;)

**Comment by varmenise** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:

**Pull request merged**
