### PR TITLE
Remove “formerly known” text

### PR DESCRIPTION
**Pull request by jglick**
Reverts this part of #296 now that 1.13 has been released.

@reviewbybees esp. @recena

### CODE REVIEW

**Comment by recena** [comment]
:bee:

**Comment by recena** [comment]
@jglick Do you plan to cut a release soon? It would be interesting to keep the version (with the message: *formerly known*) some weeks. Obviously, if it finds out a critical bug a release will have to be released.

**Comment by jglick** [comment]
> Do you plan to cut a release soon?

No particular plans.

> if it finds out a critical bug a release will have to be released

If really that critical I would consider doing a cherry-pick of the bug and cutting 1.13.1 without this or other unrelated changes.

**Comment by recena** [comment]
@jglick Thanks.

**Comment by HRMPW** [comment]
looks good to me. :bee:

**Pull request merged**
