### PR TITLE
Random WorkflowTest.executorStepRestart failure on CI

### PR DESCRIPTION
**Pull request by jglick**
[This](https://jenkins.ci.cloudbees.com/job/plugins/job/workflow-plugin/org.jenkins-ci.plugins.workflow$workflow-aggregator/1025/testReport/junit/org.jenkinsci.plugins.workflow/WorkflowTest/executorStepRestart/) for example. @reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
:+1:

**Comment by jglick** [comment]
Log remains at

```
Started
Running: Allocate node : Start
Still waiting to schedule task
Waiting for next available executor
Resuming build
```

**Comment by jglick** [comment]
```
"Executor #0 for slave0 : executing PlaceholderExecutable::null" Id=3088 Group=main WAITING on com.google.common.util.concurrent.AbstractFuture$Sync@58687fbf
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on com.google.common.util.concurrent.AbstractFuture$Sync@58687fbf
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:275)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:111)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.getThreadSynchronously(CpsStepContext.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.doGet(CpsStepContext.java:276)
	at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:67)
	at org.jenkinsci.plugins.workflow.support.steps.ExecutorStepExecution$PlaceholderTask$PlaceholderExecutable.run(ExecutorStepExecution.java:382)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

is the problem.

**Comment by jglick** [comment]
@reviewbybees again please

**Comment by recampbell** [comment]
:+1:

**Pull request merged**
