### PR TITLE
Allow LauncherDecorator to be passed in a step context

### PR DESCRIPTION
**Pull request by jglick**
For some purposes it is useful to be able to pass in a `LauncherDecorator` as part of the context of a block step, so as to affect how commands are run within that block. This change makes that possible.

(You could already install a global `LauncherDecorator` extension, which will get called by `Node.createLauncher`, via `DefaultStepContext`.)

In the future `CoreWrapperStep` (#37) could make use of this, though `SimpleBuildWrapper` would first need to do something with its `decorateLauncher` method, along the lines of the change in https://github.com/jenkinsci/jenkins/pull/1634, and I am weary of preparing core patches for the moment.

The comment in the `ReadFileStep` constructor talks about contextual `LauncherDecorator`s, though in the context of _enforced_ decoration for security purposes (probably via an `@Extension`), so it is not really applicable here.

As I noted in a comment to https://github.com/jenkinsci/maven-interceptors/pull/4 (and then filed as [JENKINS-21746](https://issues.jenkins-ci.org/browse/JENKINS-21746)), for some purposes just changing `Launcher` parameters might not suffice; we might need to be able to affect other aspects of external processes, such as a socket location for callbacks to the Jenkins slave agent. However this is only known to matter for native Maven projects, not Workflow.

@reviewbybees

### CODE REVIEW

**Comment by stephenc** [comment]
:+1: looks ok from what I understand

**Comment by recampbell** [comment]
:+1:

**Comment by tfennelly** [comment]
:+1:

**Comment by jglick** [comment]
Snapshot information for `master` @ 537a8e31f3979af70861ebc26219c038f83198b7 incl. #112:

```
workflow-pom-1.6-20150408.121903-1.pom
workflow-step-api-1.6-20150408.121918-1.hpi
workflow-step-api-1.6-20150408.121918-1.pom
workflow-step-api-1.6-20150408.121918-1.jar
workflow-step-api-1.6-20150408.121918-1-tests.jar
workflow-api-1.6-20150408.121938-1.hpi
workflow-api-1.6-20150408.121938-1.pom
workflow-api-1.6-20150408.121938-1.jar
workflow-support-1.6-20150408.121948-1.hpi
workflow-support-1.6-20150408.121948-1.pom
workflow-support-1.6-20150408.121948-1.jar
workflow-support-1.6-20150408.121948-1-tests.jar
workflow-basic-steps-1.6-20150408.122005-1.hpi
workflow-basic-steps-1.6-20150408.122005-1.pom
workflow-basic-steps-1.6-20150408.122005-1.jar
workflow-durable-task-step-1.6-20150408.122014-1.hpi
workflow-durable-task-step-1.6-20150408.122014-1.pom
workflow-durable-task-step-1.6-20150408.122014-1.jar
workflow-scm-step-1.6-20150408.122022-1.hpi
workflow-scm-step-1.6-20150408.122022-1.pom
workflow-scm-step-1.6-20150408.122022-1.jar
workflow-cps-1.6-20150408.122034-1.hpi
workflow-cps-1.6-20150408.122034-1.pom
workflow-cps-1.6-20150408.122034-1.jar
workflow-cps-1.6-20150408.122034-1-tests.jar
workflow-cps-global-lib-1.6-20150408.122054-1.hpi
workflow-cps-global-lib-1.6-20150408.122054-1.pom
workflow-cps-global-lib-1.6-20150408.122054-1.jar
workflow-job-1.6-20150408.122102-1.hpi
workflow-job-1.6-20150408.122102-1.pom
workflow-job-1.6-20150408.122102-1.jar
workflow-aggregator-1.6-20150408.122117-1.hpi
workflow-aggregator-1.6-20150408.122117-1.pom
workflow-aggregator-1.6-20150408.122117-1.jar
workflow-aggregator-1.6-20150408.122117-1-tests.jar
```

**Pull request merged**
