### PR TITLE
Added description

### PR DESCRIPTION
**Pull request by kohsuke**
Among other places, this shows up in the setup wizard to explain what this plugin is.

@reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
Screen shot:
screen shot

**Comment by jglick** [comment]
:bug: for missing corresponding edits to `index.jelly`.

**Comment by jglick** [comment]
BTW please file PRs from forks, not origin branches.

**Comment by jglick** [comment]
auto:bee:

**Comment by svanoort** [comment]
:bee:

**Pull request merged**
