### PR TITLE
helloWorld global example didn't actually work.

### PR DESCRIPTION
**Pull request by abayer**
Mismatch between parameter and variable names - fixed it to be "name"
in both places.

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
@abayer Is there JIRA issue for this?

**Comment by jtnord** [comment]
:bee:

**Comment by christ66** [comment]
:bee:

**Comment by recena** [comment]
Maybe @jglick says *Not JIRA issue required for that*, but...	who knows.

**Comment by abayer** [comment]
Yeah, I didn't bother with a JIRA 'cos, well, it's a trivial docs change. =)

**Comment by jglick** [comment]
:bee:

**Pull request merged**
