### PR TITLE
Export the Branch & SCM to REST

### PR DESCRIPTION
**Pull request by jglick**
Works in tandem with https://github.com/jenkinsci/branch-api-plugin/pull/29.

@reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
:bee:

**Comment by mslusarczyk** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

(but pointless unless and until https://github.com/jenkinsci/branch-api-plugin/pull/29 is merged)

**Comment by jglick** [comment]
Merging optimistically.

**Pull request merged**
