### PR TITLE
[JENKINS-31153] WikiPage URL renamed

### PR DESCRIPTION
**Pull request by recena**
As part of [JENKINS-31153](https://issues.jenkins-ci.org/browse/JENKINS-31153)

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
It has not been renamed yet

**Comment by recena** [comment]
@oleg-nenashev I know it.

**Comment by jglick** [comment]
I renamed the wiki page. But :bug: you must edit `<url>` in each child POM. (Maven tries to append a module name to inherited URLs, which does not work for Jenkins plugins, so each overrides this from the parent.)

**Comment by recena** [comment]
@jglick The URLs were modified.

**Comment by recena** [comment]
@jglick Don't forget to edit the repository description

**Comment by jglick** [comment]
:bee:

**Comment by jglick** [comment]
> Don't forget to edit the repository description

Done, thanks for tip.

**Comment by amuniz** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
