### PR TITLE
Fix demo image assembly

### PR DESCRIPTION
**Pull request by tfennelly**
- [x] Update Jetty version. Original no longer available for download.
- [x] Set ownership on the jetty logs dir for user jenkins. Otherwise, results in write failures when demo is running.
- [x] Set ownership on the jetty/webapps dir for user jenkins.

I also see `hudson.model.Computer$TerminationRequest` exceptions while the build is running ([see gist](https://gist.github.com/tfennelly/252efe7f9d34b90e14b5) ). These same exceptions happen when I pull and run the latest published image (so is not a regression). The demo runs fine.

I did not update the demo to use v1.10.1 of the workflow plugins, or to use the 1.625.1 jenkins docker image, but I did change and test it locally and it worked fine.

### CODE REVIEW

**Comment by tfennelly** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by jglick** [comment]
The exceptions are a bug in core, I think. I drew @kohsuke’s attention to them a while back but it is probably on @oleg-nenashev to follow up now. Easily reproduced just by running the functional tests in `mock-slave`.

**Comment by jglick** [comment]
Can you explain more about the `chown`? What error did you see? Is it related to the Jetty version? It worked before as far as I know, so I am curious why this is coming up now.

Anyway, the `Dockerfile` does specify that `jetty.sh` be run as `jenkins`, so it seems right. :bee:

**Comment by tfennelly** [comment]
@jglick You get write permission exceptions without those `chown` changes. Right, these errors do not happen with the older version of Jetty, so something must have changed there ... I didn't bother digging in to find out.

**Pull request merged**
