### PR TITLE
[JENKINS-33256] Calling SCMSource.getTrustedRevision

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/5.

@reviewbybees esp. @stephenc

### CODE REVIEW

**Comment by stephenc** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by KostyaSha** [comment]
Status?

**Comment by jglick** [comment]
I ran out of time to try using the new API and confirm that it solves the problem. On my list.

**Comment by KostyaSha** [comment]
@jglick i see no examples or description of supporting multibranches

**Comment by jglick** [comment]
Because the proposed usage is in a plugin which is currently not OSS.

**Comment by kzantow** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

(but pointless to merge unless and until https://github.com/jenkinsci/github-branch-source-plugin/pull/29 is)

**Comment by jglick** [comment]
Actually I take that back—Pipeline has a more heavyweight release process so there might be a timing advantage in having this released earlier. Also I know of at least one other `SCMSource` which might be able to take advantage of this (@amuniz). The patch should be safe enough since `getTrustedRevision` defaults to just returning its argument, so the worst that can happen is that the API turns out to be not as useful as originally thought and must be deprecated.

An `scm-api` 1.1 release is a prerequisite, though.

**Pull request merged**
