### PR TITLE
Wrap PrintWriter around StringWriter because print stack trace does n…

### PR DESCRIPTION
**Pull request by ganthore**
…ot accept StringWriter as a method.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
PrintWriter does not specify the encoding. It may be a bad approach to recommend it in docs. http://stackoverflow.com/questions/2822005/java-difference-between-printstream-and-printwriter

**Comment by stephenc** [comment]
@oleg-nenashev given that this is a `StringWriter` that is being wrapped, you do not need to specify encoding. You only need to specify the encoding if you are pushing all the way down to an encoded `byte[]` but as this is going to a `String` then `PrintWriter` is actually perfectly acceptable.

**Comment by oleg-nenashev** [comment]
OK, then :bee:

**Comment by jglick** [comment]
:bee: though it occurs to me that `hudson.Functions.printThrowable` could be used instead.

**Pull request merged**
