### PR TITLE
[JENKINS-32925] Handle recursion

### PR DESCRIPTION
**Pull request by kohsuke**
Use stack to keep track of traversal.

Counter proposal to https://github.com/jenkinsci/structs-plugin/pull/1

@reviewbybees in particular @kwhetstone

### CODE REVIEW

**Comment by jglick** [comment]
:bug: forgot `dsld` and `gdsl` views

**Comment by kohsuke** [comment]
I didn't forget dsld and gdsl. Those do not have the recursion so they are not affected by this problem.

**Comment by jglick** [comment]
OK :bee: in that case.

**Comment by kwhetstone** [comment]
I'm fine with moving the stack management to the classes that use the DescribableModel, but there should be some doc there so anyone who uses this knows that recursion could cause a problem.

**Comment by kwhetstone** [comment]
:bee:

**Pull request merged**
