### PR TITLE
Verifying that MultiBranchProject.BranchSourceList works

### PR DESCRIPTION
**Pull request by jglick**
Tests https://github.com/jenkinsci/branch-api-plugin/pull/11.

@reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
:bee: (I guess you have done a manual `mvn deploy` of the upstream PR? I don't know how the test passes otherwise).

**Comment by recena** [comment]
:bee:

**Comment by tfennelly** [comment]
:bee:

**Comment by jglick** [comment]
> I guess you have done a manual `mvn deploy` of the upstream PR?

Yes.

**Pull request merged**
