### PR TITLE
[JENKINS-32819] Fix script compilation check when CSRF is enabled

### PR DESCRIPTION
**Pull request by amuniz**
[JENKINS-32819](https://issues.jenkins-ci.org/browse/JENKINS-32819)

@reviewbybees

### CODE REVIEW

**Comment by tfennelly** [comment]
:bee: LGTM

**Comment by tfennelly** [comment]
@amuniz however, as we were saying yesterday, it would be nice to create an NPM package that contains a module to do this kind of thing without resorting to global poop (`Ajax`).

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by amuniz** [comment]
@tfennelly 
> it would be nice to create an NPM package that contains a module to do this kind of thing without resorting to global poop (Ajax).

Yeah, agree, but let's fix this and let's do that in different PR, ok?

**Comment by amuniz** [comment]
@reviewbybees done

**Comment by tfennelly** [comment]
> Yeah, agree, but let's fix this and let's do that in different PR, ok?

Oh absolutely !!  Sorry, I don't mean that as a distraction here.

**Pull request merged**
