### PR TITLE
Random test failure

### PR DESCRIPTION
**Pull request by jglick**
Observed in #62. @reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
And often in recent days, the whole test run blows up with this mystery error:

```
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:312)
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1142)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at org.jvnet.hudson.test.JenkinsRule$7$Jpl.resolveDependencies(JenkinsRule.java:1615)
	at org.jvnet.hudson.test.JenkinsRule$7.decorateHome(JenkinsRule.java:1557)
	at org.jvnet.hudson.test.JenkinsRule.newHudson(JenkinsRule.java:533)
	at org.jvnet.hudson.test.JenkinsRule.before(JenkinsRule.java:331)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:480)
```

which looks like something wrong with the CI environment but I do not know where to start.

**Comment by stephenc** [comment]
:+1:

**Comment by tfennelly** [comment]
:+1:

**Comment by jglick** [comment]
Did not work, still fails randomly, I suspect because the flag is not saved in the first Jenkins run, and it actually matters in the second run.

**Pull request merged**
