### PR TITLE
Workflow script is a proud first class citizen - own it

### PR DESCRIPTION
**Pull request by michaelneale**
Groovy CPS DSL means not a lot to most, and to those who do know that TMA means, they already know it, so they don't need to be told it. flow.groovy should be "workflow script"

### CODE REVIEW

**Comment by apemberton** [comment]
+1

Perhaps we should take a pass at UX tweak like this to workflow?

**Comment by michaelneale** [comment]
@recena I will fix the java doc too and squash.

**Comment by jglick** [comment]
:bee:, been meaning to do this for a long time, just never got around to it!

**Comment by jglick** [comment]
> replace also other occurrences in Javadoc

The only place I see _Groovy CPS_ in Javadoc is in `CpsFlowExecution`, and if you are reading that you had better know what _Groovy CPS_ means. :-) So I think this is complete as is.

**Comment by recena** [comment]
@jglick Yes, I was thinking about this file:

https://github.com/jenkinsci/workflow-plugin/blob/master/cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L112

https://github.com/jenkinsci/workflow-plugin/blob/master/cps/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L808

**Comment by recena** [comment]
:bee:

**Comment by svanoort** [comment]
:bee:  and :beer:  for the Austin Powers macro use!

**Comment by michaelneale** [comment]
Thanks @jglick, agree, the javadocs are probably the place to own up to it being groovy. For most people its very high level and I even could describe it as "groovy or javascript like". I don't expect there is another non groovy implementation of the script for some time but if/when there is, can revisit how these choices are presented. 

VERY HAPPY ABOUT THIS 

\o/

**Pull request merged**
