### PR TITLE
Direct access to build

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-26834](https://issues.jenkins-ci.org/browse/JENKINS-26834) and then [JENKINS-25851](https://issues.jenkins-ci.org/browse/JENKINS-25851)

- [X] allow `build` object to be used from the flow script
- [X] `RunPickle` to allow builds to be serialized
- [X] access to build history, status
- [x] special permission to update the `result`, `description`, or `displayName` of the current build
- [x] proper return value for (blocking) `build`
- [x] option to not fail if downstream build fails
- [x] access to downstream build variables

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees now done from my perspective.

**Comment by jglick** [comment]
In consultation with @jtnord with @kohsuke we agreed to always offer a wrapper pojo for builds, but to offer the raw `Run` as a backdoor for advanced use cases (not whitelisted for the sandbox).

**Comment by jglick** [comment]
@reviewbybees back in play.

**Comment by jglick** [comment]
The `InputStepTest.test_cancel_run_by_input` failure looks random (and I cannot reproduce locally in this branch). https://github.com/jenkinsci/jenkins/commit/9a63158 promises to produce a more useful diagnostic message.

**Comment by tfennelly** [comment]
:+1:

**Comment by kohsuke** [comment]
:+1:

**Pull request merged**
