### PR TITLE
[JENKINS-26619] DescribableHelper does not handle GitSCMExtension

### PR DESCRIPTION
**Pull request by ndeloof**
[JENKINS-26619](https://issues.jenkins-ci.org/browse/JENKINS-26619)

@reviewByBees this also cover #685

### CODE REVIEW

**Comment by jglick** [comment]
@ndeloof I suggest starting PRs from a forked repo to avoid bugs in (a) the JIRA notification daemon and (b) PR builder; except for complex changes where you expect multiple committers.

**Comment by jglick** [comment]
This causes multiple test regressions. Anyway any change to `DescribableHelper` must be accompanied by a new unit test in `DescribableHelperTest`. They are not difficult to write.

**Comment by ndeloof** [comment]
I indeed have seen test regression, don't understand how this could work using isAssignableFrom the wrong way. Will run them in a debugger.

**Comment by jglick** [comment]
Well I would start by reverting your current change, then writing a test reproducing the condition described in the issue.

**Comment by jglick** [comment]
It is not necessary to close a PR, you can just push follow-up commits as needed.

**Comment by jglick** [comment]
`isAssignableFrom` was in fact in the right direction (the method name was misleading); the problem was related but different.

**Pull request closed without merging**
