### PR TITLE
Create Samples

### PR DESCRIPTION
**Pull request by estheryouhana**
new file for Samples

### CODE REVIEW

**Comment by jglick** [comment]
Would probably want it to be `SAMPLES.md`.

**Comment by jglick** [comment]
Waiting for some samples to be added. :-)

**Comment by estheryouhana** [comment]
I will add -- I promise! I have been focusing on use cases Harpreet
targeted ((Nokia, LV =, dev’t cloud). I was told Nokia as a use case was
already completed.

**Comment by jglick** [comment]
Nothing here yet, so closing. Reopen if you add some (just push to the same branch).

**Pull request closed without merging**
