### PR TITLE
Extend JENKINS-30744 test to confirm that it is unaffected by JENKINS-29603

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-29603](https://issues.jenkins-ci.org/browse/JENKINS-29603) should not affect multibranch (AFAICT) so https://github.com/jenkinsci/git-plugin/pull/369 is not needed to support [JENKINS-30744](https://issues.jenkins-ci.org/browse/JENKINS-30744).

@reviewbybees & FYI @MarkEWaite

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by amuniz** [comment]
@jglick Tests passed this time! Could it be something related to jenkins.ci.cloudbees.com specifically?

**Comment by amuniz** [comment]
:bee: BTW

**Comment by jglick** [comment]
> Could it be something related to jenkins.ci.cloudbees.com specifically?

Yes, it is an environmental failure. See https://github.com/jenkinsci/jenkins/pull/1826.

**Pull request merged**
